# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

###
# создание продукта
POST http://localhost:8000/api/v1/products/
Content-Type: application/json

{
  "title": "Помидор",
  "description": "Лучшие помидоры на рынке"
}

###

# получение продуктов
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###

# обновление продукта
PATCH http://localhost:8000/api/v1/products/1/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE http://localhost:8000/api/v1/products/4/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET http://localhost:8000/api/v1/products/?search=помидор
Content-Type: application/json

###

# создание склада
POST http://localhost:8000/api/v1/stocks/
Content-Type: application/json

{
  "address": "ггг",
  "positions": [
    {
      "product": 1,
      "quantity": 120,
      "price": 90
    },
    {
      "product": 2,
      "quantity": 600,
      "price": 150
    }
  ]
}

###

# обновляем записи на складе
PATCH http://localhost:8000/api/v1/stocks/3/
Content-Type: application/json

{
  "address": "vvv",
  "positions": [
    {
      "product": 1,
      "quantity": 90,
      "price": 120
    },
    {
      "product": 2,
      "quantity": 120,
      "price": 350
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET http://localhost:8000/api/v1/stocks/?products=2
Content-Type: application/json
